/*
** gl_levelmesh.cpp
**
** GL33 vertex GPU objects for the level-mesh draw path (ticket 03, chunk
** D1). See gl_levelmesh.h for the object model.
**
** Attribute binding table (32-byte levelmesh::LevelMeshVertex, stride 32;
** locations are the fixed VATTR_* indices, matching the
** layout(location=N) inputs generated by ShaderInputsOutputs::
** GenerateInputsOutputs and consumed by wadsrc/static/shaders/glsl/
** levelmesh.vp):
**
**   location  attribute    GL type     offset  C++ field
**   --------  -----------  ----------  ------  --------------------------
**   0         aPosition    GL_FLOAT x3 0       x, y, slotA
**   1         aTexCoord    GL_FLOAT x2 16      u, slotB
**   6         aLightmap    GL_FLOAT x3 20      lmu, lmv, float(surfaceIndex)
**
**   4 (aNormal) is deliberately left unbound: the 32-byte pool carries no
**   normal field. An unbound vertex attribute reads as (0,0,0,1);
**   levelmesh.fp guards on dot(vWorldNormal, vWorldNormal) > 0.5 and takes
**   its no-normal fallback branch. Chunk E/F must derive the per-surface
**   normal in the VS from the plane records (or extend the vertex) before
**   normal-based shading can be A/B-validated.
**
**---------------------------------------------------------------------------
**
** Copyright 2026 UZDoom Maintainers and Contributors
**
** SPDX-License-Identifier: GPL-3.0-or-later
**
**---------------------------------------------------------------------------
**
*/

#include <cstring>
#include "gl_load.h"
#include "gl_buffers.h"
#include "gl_renderer.h"
#include "gl_levelmesh.h"
#include "buffers.h"

namespace OpenGLRenderer
{

FGLLevelMesh *GLLevelMesh = nullptr;

FGLLevelMesh::~FGLLevelMesh()
{
	Destroy();
}

//==========================================================================
//
// Delete the VAOs / IBOs. The vertex pool buffer itself is a permanent
// member; its storage is replaced by SetData on the next SetMesh.
//
//==========================================================================

void FGLLevelMesh::Destroy()
{
	// A VAO cannot be deleted while it is the current VAO; rebind the
	// renderer's default VAO first.
	if (GLRenderer != nullptr)
		glBindVertexArray(GLRenderer->mVAOID);
	else
		glBindVertexArray(0);

	if (mVAOs.Size() > 0)
		glDeleteVertexArrays((GLsizei)mVAOs.Size(), mVAOs.Data());
	mVAOs.Clear();
	mRegionIBOs.Clear();
	mGpuPool.Clear();
	mMesh = nullptr;
}

//==========================================================================
//
// Build the vertex pool VBO and the per-region IBOs / VAOs.
//
//==========================================================================

void FGLLevelMesh::SetMesh(const levelmesh::FLevelMesh *mesh)
{
	if (mesh == mMesh) return;
	Destroy();
	mMesh = mesh;
	if (mesh == nullptr) return;

	// Repack the 32-byte pool for the GL attribute layout: byte 28 carries
	// float(surfaceIndex) — GLSL 330 cannot bit-cast the raw uint32 through
	// a float attribute, and the VS recovers the index with int(). The float
	// value is exact for indices below 2^24.
	mGpuPool.Resize(mesh->vertices.Size());
	for (size_t i = 0; i < mGpuPool.Size(); i++)
	{
		mGpuPool[i] = mesh->vertices[i];
		float fidx = float(mesh->vertices[i].surfaceIndex);
		memcpy(&mGpuPool[i].surfaceIndex, &fidx, sizeof(float));
	}
	IVertexBuffer &vbo = mVertexPool;
	vbo.SetData(mGpuPool.Size() * sizeof(levelmesh::LevelMeshVertex), mGpuPool.Data(), BufferUsageType::Static);

	// One VAO per region: the pool's attribute bindings plus the region's
	// IBO bound on GL_ELEMENT_ARRAY_BUFFER.
	const size_t stride = sizeof(levelmesh::LevelMeshVertex);
	mRegionIBOs.Resize(mesh->regionIBOs.Size());
	mVAOs.Resize(mesh->regionIBOs.Size());
	for (size_t r = 0; r < mesh->regionIBOs.Size(); r++)
	{
		const TArray<uint32_t> &ibo = mesh->regionIBOs[r];
		mRegionIBOs[r] = std::make_unique<GLIndexBuffer>();
		IIndexBuffer &iboBuffer = *mRegionIBOs[r];
		iboBuffer.SetData(ibo.Size() * sizeof(uint32_t), ibo.Data(), BufferUsageType::Static);

		unsigned int vao = 0;
		glGenVertexArrays(1, &vao);
		glBindVertexArray(vao);
		// GLVertexBuffer::Bind(int*) would also (re)set all attribute pointers;
		// only the raw buffer bind is wanted here.
		static_cast<GLBuffer &>(mVertexPool).Bind();
		glVertexAttribPointer(VATTR_VERTEX, 3, GL_FLOAT, GL_FALSE, (GLsizei)stride, (const void *)(uintptr_t)0);	// aPosition.xyz = x, y, slotA
		glEnableVertexAttribArray(VATTR_VERTEX);
		glVertexAttribPointer(VATTR_TEXCOORD, 2, GL_FLOAT, GL_FALSE, (GLsizei)stride, (const void *)(uintptr_t)16);	// aTexCoord.xy = u, slotB
		glVertexAttribPointer(VATTR_LIGHTMAP, 3, GL_FLOAT, GL_FALSE, (GLsizei)stride, (const void *)(uintptr_t)20);	// aLightmap = lmu, lmv, float(surfaceIndex)
		glEnableVertexAttribArray(VATTR_LIGHTMAP);
		// VATTR_NORMAL is left unbound, see the table in the file header.
		mRegionIBOs[r]->Bind();
		// Restore the renderer's default VAO; the attribute pointers above
		// were captured into the new VAO, not the default one.
		if (GLRenderer != nullptr)
			glBindVertexArray(GLRenderer->mVAOID);
		else
			glBindVertexArray(0);
		mVAOs[r] = vao;
	}
}

}
